### ISSUE TITLE
Add Kubernetes discovery possibility

### ISSUE THREAD

**Issue by git001** [rqlite/rqlite-disco-clients#3]
It would be nice that the rqlite can discover the instances via [StatefulSet](https://kubernetes.io/docs/reference/kubernetes-api/workloadresources/stateful-set-v1/).

When I want to add this feature is there a development documentation or should I read the code?
What's the best client to start, consul or etcd?

**Comment by otoolep** [comment]
That's the plan, it's a top priority. I hope to add support for Kubernetes very soon.

Consul or etcd, up to you. rqlite supports either just as well.

**Comment by git001** [comment]
With this repo can a statefull set be setuped and discoverd via DNS.
https://github.com/rqlite/kubernetes-configuration
